version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppassword}@db:5432/${POSTGRES_DB:-appdb}?schema=public
      FRONTEND_URL: http://localhost:5173
      JWT_ACCESS_SECRET: supersecretaccess
      JWT_REFRESH_SECRET: supersecretrefresh
      CORS_ORIGIN: http://localhost:5173
      COOKIE_SECURE: "false"
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"

volumes:
  db_data:


